{
    "type": "bundle",
    "id": "bundle--f84ff2de-76fc-4ff0-8ab2-5e806210d149",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--13c3d2bc-77e5-4302-b7e4-f5c68cce2508",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-16T00:43:25.059487Z",
            "modified": "2025-05-16T00:43:25.059487Z",
            "name": "CVE-2025-4516",
            "description": "There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-4516"
                }
            ]
        }
    ]
}